# Lift configuration
# Reference https://help.sonatype.com/lift/configuration-reference

# setup = <path to setup script>
# build = ENV= <env> <build option> [target]
build = "./gradlew build -x test -x dockerClean -x dockerPrepare -x dockerRun -x dockerRunStatus -x dockerStop"

# importantRules = <exclusive list of issues to report back to user>
# ignoreRules = <list of issues never to report to the user>
# ignoreFiles = <gitignore format string of files to ignore>

## tools = <infer | errorprone | eslint | hlint | findsecbugs >
tools = ["infer", "findsecbugs"]

# disableTools = <list of tools to not run on the project>
disableTools = ["errorprone"]

# customTools = <list of user-provided tools conforming to a tool API>
# allow = <list of users whose pull requests can trigger analysis>
# jdkVersion = <jdk version>
jdkVersion = "11"

# summaryComments = <true or false (defaults to false)
summaryComments = false
