package com.github.nagyesta.lowkeyvault.service.key.impl;

import com.github.nagyesta.lowkeyvault.mapper.v7_2.key.AesJsonWebKeyImportRequestConverter;
import com.github.nagyesta.lowkeyvault.mapper.v7_2.key.EcJsonWebKeyImportRequestConverter;
import com.github.nagyesta.lowkeyvault.mapper.v7_2.key.RsaJsonWebKeyImportRequestConverter;
import com.github.nagyesta.lowkeyvault.model.v7_2.common.constants.RecoveryLevel;
import com.github.nagyesta.lowkeyvault.model.v7_2.key.constants.KeyCurveName;
import com.github.nagyesta.lowkeyvault.model.v7_2.key.constants.KeyOperation;
import com.github.nagyesta.lowkeyvault.model.v7_2.key.request.JsonWebKeyImportRequest;
import com.github.nagyesta.lowkeyvault.service.common.impl.BaseVaultFakeImpl;
import com.github.nagyesta.lowkeyvault.service.key.KeyVaultFake;
import com.github.nagyesta.lowkeyvault.service.key.ReadOnlyKeyVaultKeyEntity;
import com.github.nagyesta.lowkeyvault.service.key.ReadOnlyRotationPolicy;
import com.github.nagyesta.lowkeyvault.service.key.RotationPolicy;
import com.github.nagyesta.lowkeyvault.service.key.id.KeyEntityId;
import com.github.nagyesta.lowkeyvault.service.key.id.VersionedKeyEntityId;
import com.github.nagyesta.lowkeyvault.service.key.util.PeriodUtil;
import com.github.nagyesta.lowkeyvault.service.vault.VaultFake;
import org.jspecify.annotations.Nullable;
import org.springframework.util.Assert;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

public class KeyVaultFakeImpl
        extends BaseVaultFakeImpl<KeyEntityId, VersionedKeyEntityId, ReadOnlyKeyVaultKeyEntity, KeyVaultKeyEntity<?, ?>>
        implements KeyVaultFake {

    private final RsaJsonWebKeyImportRequestConverter rsaConverter = new RsaJsonWebKeyImportRequestConverter();
    private final EcJsonWebKeyImportRequestConverter ecConverter = new EcJsonWebKeyImportRequestConverter();
    private final AesJsonWebKeyImportRequestConverter aesConverter = new AesJsonWebKeyImportRequestConverter();
    private final ConcurrentMap<String, RotationPolicy> rotationPolicies = new ConcurrentHashMap<>();

    public KeyVaultFakeImpl(
            final VaultFake vaultFake,
            final RecoveryLevel recoveryLevel,
            @Nullable final Integer recoverableDays) {
        super(vaultFake, recoveryLevel, recoverableDays);
    }

    @Override
    protected VersionedKeyEntityId createVersionedId(
            final String id,
            final String version) {
        return new VersionedKeyEntityId(vaultFake().baseUri(), id, version);
    }

    @Override
    public VersionedKeyEntityId createKeyVersion(
            final String keyName,
            final KeyCreateDetailedInput input) {
        Assert.isTrue(!input.isManaged() || (input.getExpiresOn() != null && input.getNotBefore() != null),
                "Managed key (name=" + keyName + ") must have notBefore and expiresOn parameters set!");
        final var keyEntityId = input.getKey().getKeyType().createKey(this, keyName, input.getKey());
        setKeyOperations(keyEntityId, input.getKeyOperations());
        //avoid overwriting expiry if it was generated by the rotation policy
        if (getEntities().getReadOnlyEntity(keyEntityId).getExpiry().isEmpty()) {
            setExpiry(keyEntityId, input.getNotBefore(), input.getExpiresOn());
        }
        setEnabled(keyEntityId, Optional.ofNullable(input.getEnabled()).orElse(true));
        setManaged(keyEntityId, input.isManaged());
        addTags(keyEntityId, input.getTags());
        return keyEntityId;
    }

    @Override
    public VersionedKeyEntityId importKeyVersion(
            final String keyName,
            final KeyImportInput input) {
        final var keyEntityId = new VersionedKeyEntityId(vaultFake().baseUri(), keyName);
        return importKeyVersion(keyEntityId, input);
    }

    @Override
    public VersionedKeyEntityId importKeyVersion(
            final VersionedKeyEntityId keyEntityId,
            final KeyImportInput input) {
        Assert.isTrue(input.getHsm() == null || input.getHsm() == input.getKey().getKeyType().isHsm(),
                "When HSM property is set in request, key type must match it.");
        final var keyType = Objects.requireNonNull(input.getKey()).getKeyType();
        keyType.importKey(this, keyEntityId, input.getKey());
        setKeyOperations(keyEntityId, input.getKey().getKeyOps());
        addTags(keyEntityId, input.getTags());
        setExpiry(keyEntityId, input.getNotBefore(), input.getExpiresOn());
        setEnabled(keyEntityId, Optional.ofNullable(input.getEnabled()).orElse(true));
        setManaged(keyEntityId, input.isManaged());
        setCreatedAndUpdatedOn(keyEntityId, input.getCreatedOn(), input.getUpdatedOn());
        return keyEntityId;
    }

    @Override
    public VersionedKeyEntityId importRsaKeyVersion(
            final VersionedKeyEntityId keyEntityId,
            final JsonWebKeyImportRequest key) {
        final var keyType = Objects.requireNonNull(key).getKeyType();
        Assert.isTrue(keyType.isRsa(), "RSA key expected, but found: " + keyType.name());
        final var keyEntity = new RsaKeyVaultKeyEntity(keyEntityId, vaultFake(), rsaConverter.convert(key),
                rsaConverter.getKeyParameter(key), keyType.isHsm());
        setExpiryBasedOnRotationPolicy(keyEntityId, keyEntity);
        return addVersion(keyEntityId, keyEntity);
    }

    @Override
    public VersionedKeyEntityId importEcKeyVersion(
            final VersionedKeyEntityId keyEntityId,
            final JsonWebKeyImportRequest key) {
        final var keyType = Objects.requireNonNull(key).getKeyType();
        Assert.isTrue(keyType.isEc(), "EC key expected, but found: " + keyType.name());
        final var keyEntity = new EcKeyVaultKeyEntity(keyEntityId, vaultFake(), ecConverter.convert(key),
                ecConverter.getKeyParameter(key), keyType.isHsm());
        setExpiryBasedOnRotationPolicy(keyEntityId, keyEntity);
        return addVersion(keyEntityId, keyEntity);
    }

    @Override
    public VersionedKeyEntityId importOctKeyVersion(
            final VersionedKeyEntityId keyEntityId,
            final JsonWebKeyImportRequest key) {
        final var keyType = Objects.requireNonNull(key).getKeyType();
        Assert.isTrue(keyType.isOct(), "OCT key expected, but found: " + keyType.name());
        Assert.isTrue(keyType.isHsm(), "OCT keys are only supported using HSM.");
        final var keyEntity = new AesKeyVaultKeyEntity(keyEntityId, vaultFake(), aesConverter.convert(key),
                aesConverter.getKeyParameter(key), keyType.isHsm());
        setExpiryBasedOnRotationPolicy(keyEntityId, keyEntity);
        return addVersion(keyEntityId, keyEntity);
    }

    @Override
    public VersionedKeyEntityId createRsaKeyVersion(
            final String keyName,
            final RsaKeyCreationInput input) {
        final var keyEntityId = new VersionedKeyEntityId(vaultFake().baseUri(), keyName);
        final var keyEntity = new RsaKeyVaultKeyEntity(keyEntityId, vaultFake(),
                input.getKeyParameter(), input.getPublicExponent(), input.getKeyType().isHsm());
        setExpiryBasedOnRotationPolicy(keyEntityId, keyEntity);
        return addVersion(keyEntityId, keyEntity);
    }

    @Override
    public VersionedKeyEntityId createEcKeyVersion(
            final String keyName,
            final EcKeyCreationInput input) {
        final var keyEntityId = new VersionedKeyEntityId(vaultFake().baseUri(), keyName);
        input.getKeyType().validate(input.getKeyParameter(), KeyCurveName.class);
        final var keyEntity = new EcKeyVaultKeyEntity(
                keyEntityId, vaultFake(), input.getKeyParameter(), input.getKeyType().isHsm());
        setExpiryBasedOnRotationPolicy(keyEntityId, keyEntity);
        return addVersion(keyEntityId, keyEntity);
    }

    @Override
    public VersionedKeyEntityId createOctKeyVersion(
            final String keyName,
            final OctKeyCreationInput input) {
        final var keyEntityId = new VersionedKeyEntityId(vaultFake().baseUri(), keyName);
        Assert.isTrue(input.getKeyType().isHsm(), "OCT keys are only supported using HSM.");
        final var keyEntity = new AesKeyVaultKeyEntity(keyEntityId, vaultFake(),
                input.getKeyParameter(), input.getKeyType().isHsm());
        setExpiryBasedOnRotationPolicy(keyEntityId, keyEntity);
        return addVersion(keyEntityId, keyEntity);
    }

    @Override
    public void setKeyOperations(
            final VersionedKeyEntityId keyEntityId,
            @Nullable final List<KeyOperation> keyOperations) {
        final var operations = Optional.ofNullable(keyOperations).orElse(Collections.emptyList());
        getEntitiesInternal().getEntity(keyEntityId).setOperations(operations);
    }

    @Override
    public void timeShift(final int offsetSeconds) {
        super.timeShift(offsetSeconds);
        rotationPolicies.values().forEach(p -> p.timeShift(offsetSeconds));
        performPastRotations();
    }

    private void performPastRotations() {
        rotationPolicies.values().stream()
                .filter(ReadOnlyRotationPolicy::isAutoRotate)
                .forEach(this::performMissedRotationsOfPolicy);
    }

    @Override
    public @Nullable RotationPolicy rotationPolicy(final KeyEntityId keyEntityId) {
        purgeDeletedPolicies();
        return rotationPolicies.get(keyEntityId.id());
    }

    @Override
    public void setRotationPolicy(final RotationPolicy rotationPolicy) {
        final var readOnlyEntity = latestReadOnlyKeyVersion(rotationPolicy.getId());
        Assert.state(!readOnlyEntity.isManaged(), "Cannot set rotation policy to managed entity: " + rotationPolicy.getId());
        rotationPolicy.validate(readOnlyEntity.getExpiry().orElse(null));
        final var existingPolicy = rotationPolicy(rotationPolicy.getId());
        if (existingPolicy == null) {
            rotationPolicies.put(rotationPolicy.getId().id(), rotationPolicy);
        } else {
            existingPolicy.setLifetimeActions(rotationPolicy.getLifetimeActions());
            existingPolicy.setExpiryTime(rotationPolicy.getExpiryTime());
        }
    }

    @Override
    public VersionedKeyEntityId rotateKey(final KeyEntityId keyEntityId) {
        final var readOnlyEntity = latestReadOnlyKeyVersion(keyEntityId);
        return createKeyVersion(keyEntityId.id(), KeyCreateDetailedInput.builder()
                .key(readOnlyEntity.keyCreationInput())
                .keyOperations(readOnlyEntity.getOperations())
                .enabled(true)
                //never rotate managed entities
                .managed(false)
                .tags(readOnlyEntity.getTags())
                //expiry will be automatically set based on the rotation policy when created
                .build());
    }

    private void setExpiryBasedOnRotationPolicy(
            final VersionedKeyEntityId keyEntityId,
            final KeyVaultKeyEntity<?, ?> keyEntity) {
        final var expiryDays = Optional.of(rotationPolicies)
                .map(policies -> policies.get(keyEntityId.id()))
                .map(ReadOnlyRotationPolicy::getExpiryTime)
                .map(PeriodUtil::asDays);
        expiryDays.ifPresent(days -> keyEntity.setExpiry(keyEntity.getCreated().plusDays(days)));
    }

    private ReadOnlyKeyVaultKeyEntity latestReadOnlyKeyVersion(final KeyEntityId keyEntityId) {
        final var latestVersionOfEntity = getEntities().getLatestVersionOfEntity(keyEntityId);
        return getEntities().getReadOnlyEntity(latestVersionOfEntity);
    }

    private void performMissedRotationsOfPolicy(final RotationPolicy rotationPolicy) {
        final var keyEntityId = rotationPolicy.getId();
        final var latestVersionOfEntity = getEntities().getLatestVersionOfEntity(keyEntityId);
        final var readOnlyEntity = getEntities().getReadOnlyEntity(latestVersionOfEntity);
        rotationPolicy.missedRotations(readOnlyEntity.getCreated())
                .forEach(rotationTime -> simulatePointInTimeRotation(keyEntityId, rotationTime));
    }

    private void simulatePointInTimeRotation(
            final KeyEntityId keyEntityId,
            final OffsetDateTime rotationTime) {
        final var now = OffsetDateTime.now(ZoneOffset.UTC);
        final var diffSeconds = (int) (now.toEpochSecond() - rotationTime.toEpochSecond());
        final var versionedKeyEntityId = rotateKey(keyEntityId);
        getEntities().getEntity(versionedKeyEntityId, KeyVaultKeyEntity.class).timeShift(diffSeconds);
    }

    private void purgeDeletedPolicies() {
        keepNamesReadyForRemoval(rotationPolicies.keySet())
                .forEach(rotationPolicies::remove);
    }
}
