name: JavaCI

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "**/README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "pull_request_template.md"
      - ".lift/.toml"
      - "**/.lift/.toml"
      - "SECURITY.md"
      - "LICENSE"
      - ".github/**"
      - "renovate.json"
      - ".whitesource"
      - "gradle/libs.versions.toml"
      - "gradle/verification-metadata.xml"
      - "gradle/verification-metadata-clean.xml"
      - "lowkey-vault-docker/src/docker/Dockerfile"
      - "gradle/wrapper/gradle-wrapper.properties"
      - "gradle/wrapper/gradle-wrapper.jar"
      - "gradlew"
      - "gradlew.bat"
      - "config/ossindex/exclusions.txt"
      - ".idea/**"
      - ".gitignore"
      - ".qlty/**"

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      tag_name: ${{ steps.read-tag-name.outputs.RELEASE_TAG_NAME }}
    steps:
      # Set up the build environment
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
        with:
          gradle-home-cache-cleanup: true
      - name: Build with Gradle
        run: ./gradlew printVersion build
      - name: Decode key
        run: |
          mkdir -p ${{ runner.temp }}/.gnupg/
          echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode > ${{ runner.temp }}/.gnupg/secring.gpg
      - name: Docker Login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Read tag name
        id: read-tag-name
        run: |
          echo "RELEASE_TAG_NAME=$(cat ./build/version)" >> "$GITHUB_OUTPUT"
      - name: Tag version
        run: |
          git config --global user.name 'Esta Nagy'
          git config --global user.email 'nagyesta@gmail.com'
          git tag ${{ steps.read-tag-name.outputs.RELEASE_TAG_NAME }}
          git push origin ${{ steps.read-tag-name.outputs.RELEASE_TAG_NAME }}
      - name: Build with Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          ./gradlew publish publishToSonatype sonar closeAndReleaseSonatypeStagingRepository
          -x test -x dockerBuild -x dockerRun -x dockerStop
          -PgithubUser=${{ secrets.GITHUB_ACTOR }}
          -PgithubToken=${{ secrets.GITHUB_TOKEN }}
          -PossrhUsername=${{ secrets.OSSRH_USER }}
          -PossrhPassword=${{ secrets.OSSRH_PASS }}
          -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }}
          -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          -Psigning.secretKeyRingFile=${{ runner.temp }}/.gnupg/secring.gpg
      - name: Clean-up GPG key
        if: always()
        run: |
          rm -rf ${{ runner.temp }}/.gnupg/

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          TAG_NAME: ${{needs.build.outputs.tag_name }}
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ env.TAG_NAME }}",
              generate_release_notes: true,
              draft: false
            });
