name: "DependencyCheck"

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
    paths:
      - "gradle/**"
      - "config/snyk/**"
      - ".release-trigger"
      - ".snyk"
      - ".github/workflows/gradle-dependency-check.yml"
      - "lowkey-vault-docker/src/docker/Dockerfile"
  workflow_dispatch:
  schedule:
    # * is a special character in YAML, so we have to quote this string
    - cron: "0 7 * * 2,4,6"

permissions: read-all

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Configure Snyk endpoint
        run: |
          mkdir -p ~/.config/configstore/
          cp ./config/snyk/snyk.json ~/.config/configstore/snyk.json
      - name: Monitor changes with Snyk to continuously check for vulnerabilities
        uses: snyk/actions/gradle@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        if: ${{ github.event_name != 'pull_request' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: >
            --all-projects
            --org=${{ secrets.SNYK_ORG_ID }}
            --remote-repo-url=https://github.com/${{ github.repository }}/
            --target-reference=${{ github.ref_name }}
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >
            --fail-on=all
            --all-projects
            --org=${{ secrets.SNYK_ORG_ID }}
            --remote-repo-url=https://github.com/${{ github.repository }}/
            --show-vulnerable-paths=all
            --configuration-matching="^runtimeClasspath|compileClassPath|testRuntimeClasspath|testCompileClassPath$" 


