# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JavaTestMain

on:
  push:
    branches: [ main ]
    paths:
      - 'gradle/libs.versions.toml'
      - 'gradle/verification-metadata.xml'
      - 'lowkey-vault-docker/src/docker/Dockerfile'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - 'config/ossindex/exclusions.txt'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Set up build environment
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          distribution: temurin
          java-version: 11
      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Decode key
        run: |
          mkdir -p ~/.gnupg/
          echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode > ~/.gnupg/secring.gpg
      - name: Build with Gradle
        run: >
          ./gradlew printVersion build
      - name: Upload coverage to Codecov - App
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lowkey-vault-app/build/reports/jacoco/report.xml
          flags: app
      - name: Upload coverage to Codecov - Client
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lowkey-vault-client/build/reports/jacoco/report.xml
          flags: client
      - name: Upload coverage to Codecov - Testcontainers
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lowkey-vault-testcontainers/build/reports/jacoco/report.xml
          flags: testcontainers
